number1 = int(input("Nimeä yksi kokonaisluku."))
number2 = int(input("Nimeä toinen kokonaisluku."))
number3 = int(input("Nimeä kolmas kokonaisluku."))
print("Kokonaislukujen summa on", number1+number2+number3)
print("Kokonaislukujen tulo on", number1*number2*number3)
print("Kokonaislukujen keskiarvo on", round((number1+number2+number3)/3))
